### ISSUE TITLE
Export vulnerabilities by risk meter

### ISSUE THREAD

**Issue by ghlilou97** [KennaSecurity/blog_samples#67]
Hello, is there any script that allow us to export as ( csv or json ) all vulnerabilities details and also assets details by risk meter

**Comment by rick-kenna** [comment]
1. By vulnerability details, I assume you mean scanner vulnerability details.  At this time, there is no script that allows you to export all scanner vulnerability details.  This feature request is known by the developing team.
2. You can look at [asset_export.py](https://github.com/KennaSecurity/blog_samples/blob/main/python/unique_asset_tags/export_assets.py), and 'search_id': risk_meter_id, after line 36.

And by the way, I think you'll find it easier to process JSONL than JSON.
